version: '2.1'


services:
 product:
  build: productService
  mem_limit: 512m
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - SPRING_APPLICATION_NAME=productsService
  depends_on:
    mongodb:
     condition: service_healthy   
    rabbitmq:
     condition: service_healthy  

 review:
  build: reviewsService
  mem_limit: 512m
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - SPRING_APPLICATION_NAME=reviewsService
  depends_on:
   mysql:
    condition: service_healthy
   rabbitmq: 
    condition: service_healthy 

 product-composite:
  build: productComposite
  mem_limit: 512m
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - SPRING_APPLICATION_NAME=productCompositeService
  depends_on:
   rabbitmq:
    condition: service_healthy
 
 mongodb:
  image: mongo:6.0.4
  mem_limit: 256m
  ports:
   - "27017:27017"   
  command: mongod
  healthcheck:
   test: "mongostat -n 1"
   interval: 5s
   timeout: 2s
   retries: 60
   
 mysql:
  image: mysql:8.0.32
  mem_limit: 256m
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=rootpwd
   - MYSQL_DATABASE=review-db
   - MYSQL_USER=user
   - MYSQL_PASSWORD=pwd
  healthcheck:
   test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
   interval: 5s
   timeout: 2s
   retries: 60

 rabbitmq:
  image: rabbitmq:3.11.8-management
  mem_limit: 256m
  ports:
   - 5672:5672
   - 15672:15672
  healthcheck:
   test: ["CMD", "rabbitmqctl", "status"]
   interval: 5s
   timeout: 2s
   retries: 60
 
 eureka:
  build: springCloud/eurekaServer
  mem_limit: 256m
   
 gateway:
  build: springCloud/gateway
  environment:
  - SPRING_PROFILES_ACTIVE=docker
  - SERVER_SSL_KEY_STORE=file:/keystore/edge-test.p12
  - SERVER_SSL_KEY_STORE_PASSWORD=password
  volumes:
   - $PWD/keystore:/keystore
  mem_limit: 256m
  ports:
   - "8443:8443"
  depends_on:
   auth-server:
    condition: service_healthy

 auth-server:
  environment: 
   - SPRING_PROFILES_ACTIVE=docker
  build: springCloud/authorizationServer
  mem_limit: 256m
  healthcheck:
   test: ["CMD","curl", "-fs", "http://localhost:9999/actuator/health"]
   interval: 5s
   timeout: 2s
   retries: 60