spring.application.name: auth-server

server:
  port: 9999
  forward-headers-strategy: framework

app:
 eureka-username: user
 eureka-password: password
 eureke-server: localhost

eureka:
 client:
  service-url: 
   defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
  initial-instance-info-replication-interval-seconds: 5
  registryFetchIntervalSeconds: 5
 instance:
  leaseRenewalIntervalInSeconds: 5
  leaseExpirationDurationInSeconds: 5
 
management:
 endpoint:
    health:
      show-details: "ALWAYS"
 endpoints:
    web:
      exposure:
        exclude:
        - "*"

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile:
      - docker
app.eureka-server: eureka
