
spring:
 application.name: reviewsService
 cloud.config:
  failFast: false
  retry:
   initialInterval: 3000
   multiplier: 1.3
   maxInterval: 5000
   maxAttempts: 5
 config:
  import: optional:configserver:http://dev-user:dev-pwd@localhost:8888

---
spring:
  config:
    activate:
      on-profile:
      - docker
spring.config.import: configserver:http://${CONFIG_SERVER_USR}:${CONFIG_SERVER_PWD}@config-server:8888



