spring:
  application.name: eurekaServer
  cloud:
    config:
      failFast: false
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 10
  config:
    import: optional:configserver:http://dev-user:dev-pwd@config-server:8888,optional:configserver:http://dev-user:dev-pwd@localhost:8888

logging:
  level: 
   root: INFO 

---
spring:
  config:
    activate.on-profile: docker
    import: configserver:http://dev-user:dev-pwd@config-server:8888


