spring.application.name: productComposite

server:
  port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  review-service:
    host: localhost
    port: 7003


logging:
  level:
    root: INFO
    ber.com: DEBUG		

---
sspring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  product-service:
    host: product
    port: 8080
  review-service:
    host: review
    port: 8080